# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171219_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
